### ISSUE TITLE
note 标签在深色模式难以看清文字内容 

### ISSUE THREAD

**Issue by HPCesia** [everfu/hexo-solitude-tag#2]
深色模式下，note标签的浅色背景 + 与文章一样的白色字体颜色，完全看不清。
![image](https://github.com/user-attachments/assets/ebde5077-dbdf-475c-be56-6393e6a038d4)

翻了下 styl 文件发现是从 butterfly 的那个 tag 插件移植过来的，可以给 note 标签默认加上 modern 样式，这样就看得清楚字了。
![image](https://github.com/user-attachments/assets/e2608005-bed2-44bc-b7c0-aa5e1dbef069)
![image](https://github.com/user-attachments/assets/08bf8a97-940f-40f3-87e9-94cbd6aa5b6a)

**Comment by everfu** [comment]
可以直接编译仓库styl文件进行修复和pr
